name: jupyterlab-demo
channels:
- conda-forge
- defaults
dependencies:
- pip
- altair=1.2.0
- jupyterlab=0.24.1
- jupyterlab_launcher=0.2.9
- dask=0.15.0
- ipython=6.1.0
- matplotlib=2.0.2
- notebook=5.0.0
- pandas=0.20.2
- pip=9.0.1
- python=3.6.0
- scikit-image=0.13.0
- scikit-learn=0.18.1
- seaborn=0.7.1
- sympy=1.0
- tensorflow=1.1.0
- nodejs=6.11.0=0