channels:
- conda-forge
dependencies:
- jupyterlab=0.30.6
- nodejs=8.8.1
- notebook=5.2.2
- ipykernel=4.7.0
- ipywidgets=7.0.5
- widgetsnbextension==3.0.8
- altair=1.2.0
- bqplot=0.10.1
- dask=0.15.0
- matplotlib=2.1.1
- pandas=0.20.2
- pip=9.0.1
- python=3.6.0
- scikit-image=0.13.0
- scikit-learn=0.18.1
- seaborn=0.7.1
- tensorflow=1.1.0
- sympy=1.0
- pyyaml
- traittypes==0.0.6
- invoke==0.21.0
