channels:
- conda-forge
dependencies:
# Jupyter
- jupyterlab=0.34.0
- nodejs=8.9
- notebook=5.6
- nbconvert=5.3
- widgetsnbextension=3.3
# Python Kernel
- ipykernel=4.7
- ipywidgets=7.3
- ipyleaflet=0.9
- altair=1.2
- bqplot=0.11.5
- dask=0.15
- matplotlib=2.1
- pandas=0.20
- python=3.6
- scikit-image=0.13
- scikit-learn=0.19
- seaborn=0.7
- tensorflow=1.1
- sympy=1.0
- pyyaml
- traittypes==0.2.1
- invoke=0.21
# C++ Kernel
- xeus-cling=0.4.11
- xtensor=0.19.2
- xtensor-blas=0.15.1
- xwidgets=0.16.1
- xleaflet=0.6.1
# R Kernel
- r-ggplot2
- r-irkernel=0.8.11
